import { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import {
  Mic, MicOff, Volume2, VolumeX, ChevronRight, RotateCcw,
  Download, CheckCircle2, AlertCircle, Lightbulb, Trophy,
  FileText, ClipboardList, Settings, BarChart3, Star,
  Clock, Target, TrendingUp, Loader2, Play, Square,
  Upload, BookOpen, Zap, MessageSquare, ArrowRight,
  Circle, CheckCheck, XCircle
} from 'lucide-react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const STAGES = { SETUP: 'setup', READY: 'ready', INTERVIEWING: 'interviewing', FINISHED: 'finished' };

const scoreColor = (s) => {
  if (s >= 80) return 'text-emerald-400';
  if (s >= 60) return 'text-yellow-400';
  return 'text-red-400';
};
const scoreBg = (s) => {
  if (s >= 80) return 'bg-emerald-500/10 border-emerald-500/30';
  if (s >= 60) return 'bg-yellow-500/10 border-yellow-500/30';
  return 'bg-red-500/10 border-red-500/30';
};
const scoreBar = (s) => {
  if (s >= 80) return 'bg-emerald-500';
  if (s >= 60) return 'bg-yellow-500';
  return 'bg-red-500';
};

// ── PDF (unchanged logic) ──────────────────────────────────────────────────
const downloadReportPDF = (questions, answers, feedbacks, finalReport, setupData) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = 210, pageH = 297, margin = 18, contentW = 210 - 36;
  let y = 0;
  const checkPage = (needed = 12) => {
    if (y + needed > pageH - 15) { doc.addPage(); doc.setFillColor(15,23,42); doc.rect(0,0,pageW,pageH,'F'); y = 20; }
  };
  const avgScore = feedbacks.length ? Math.round(feedbacks.reduce((a,f)=>a+(f?.score||0),0)/feedbacks.length) : 0;
  doc.setFillColor(15,23,42); doc.rect(0,0,pageW,pageH,'F');
  doc.setFillColor(14,165,233); doc.rect(0,0,pageW,3,'F');
  doc.setFillColor(14,165,233); doc.roundedRect(margin,28,12,12,2,2,'F');
  doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.setTextColor(255,255,255); doc.text('R',margin+4.2,36.5);
  doc.setFontSize(13); doc.text('ResumeAI',margin+16,36.5);
  doc.setFontSize(30); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255); doc.text('Mock Interview',margin,100);
  doc.setTextColor(14,165,233); doc.text('Report',margin,115);
  doc.setFontSize(11); doc.setFont('helvetica','normal'); doc.setTextColor(148,163,184);
  doc.text(`Role: ${setupData.role||'General'}`,margin,128); doc.text(`Level: ${setupData.level||'Junior'}`,margin,137);
  const cx=pageW-margin-25,cy=108;
  doc.setFillColor(30,41,59); doc.circle(cx,cy,22,'F'); doc.setFontSize(22); doc.setFont('helvetica','bold');
  const sc=avgScore>=80?[16,185,129]:avgScore>=60?[245,158,11]:[239,68,68];
  doc.setTextColor(...sc); doc.text(`${avgScore}`,cx-(avgScore>=100?9:avgScore>=10?6:4),cy+4);
  doc.setFontSize(8); doc.setTextColor(100,116,139); doc.text('/100',cx-5,cy+12);
  const stats=[{label:'Questions',val:questions.length},{label:'Answered',val:answers.filter(Boolean).length},{label:'Avg Score',val:`${avgScore}%`}];
  stats.forEach((s,i)=>{
    const x=margin+i*60; doc.setFillColor(30,41,59); doc.roundedRect(x,155,55,24,3,3,'F');
    doc.setFont('helvetica','bold'); doc.setFontSize(14); doc.setTextColor(255,255,255); doc.text(`${s.val}`,x+6,167);
    doc.setFont('helvetica','normal'); doc.setFontSize(8); doc.setTextColor(100,116,139); doc.text(s.label,x+6,174);
  });
  if(finalReport?.summary){
    doc.setFillColor(30,41,59); doc.roundedRect(margin,190,contentW,45,4,4,'F');
    doc.setFillColor(14,165,233); doc.roundedRect(margin,190,4,45,2,2,'F');
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(14,165,233); doc.text('OVERALL SUMMARY',margin+10,200);
    doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(203,213,225);
    const lines=doc.splitTextToSize(finalReport.summary,contentW-18); doc.text(lines.slice(0,5),margin+10,208);
  }
  doc.setFontSize(8); doc.setTextColor(71,85,105); doc.text(`Generated by ResumeAI  •  ${new Date().toLocaleDateString('en-IN')}`,margin,pageH-12);
  questions.forEach((q,i)=>{
    doc.addPage(); doc.setFillColor(15,23,42); doc.rect(0,0,pageW,pageH,'F');
    const fb=feedbacks[i]; const [fr,fg,fb2]=fb?.score>=80?[16,185,129]:fb?.score>=60?[245,158,11]:[239,68,68];
    doc.setFillColor(fr,fg,fb2); doc.rect(0,0,pageW,2,'F');
    y=20; doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(fr,fg,fb2); doc.text(`QUESTION ${i+1} OF ${questions.length}`,margin,y);
    if(fb?.score!==undefined){doc.setFillColor(30,41,59);doc.roundedRect(pageW-margin-28,y-6,28,10,2,2,'F');doc.setTextColor(fr,fg,fb2);doc.text(`${fb.score}/100`,pageW-margin-22,y);}
    y+=10; doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(255,255,255);
    const qLines=doc.splitTextToSize(q.question,contentW); doc.text(qLines,margin,y); y+=qLines.length*7+8;
    if(answers[i]){
      doc.setFillColor(22,33,51); const aLines=doc.splitTextToSize(answers[i],contentW-16); const aH=aLines.length*5.5+14;
      doc.roundedRect(margin,y,contentW,aH,3,3,'F'); doc.setFont('helvetica','bold'); doc.setFontSize(7.5); doc.setTextColor(100,116,139); doc.text('YOUR ANSWER',margin+8,y+8);
      doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(203,213,225); doc.text(aLines,margin+8,y+14); y+=aH+8;
    }
    if(fb){
      if(fb.good){checkPage(20);const gLines=doc.splitTextToSize(fb.good,contentW-16);const gH=gLines.length*5.5+14;doc.setFillColor(15,35,25);doc.roundedRect(margin,y,contentW,gH,3,3,'F');doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(16,185,129);doc.text('WHAT YOU DID WELL',margin+8,y+8);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(167,243,208);doc.text(gLines,margin+8,y+14);y+=gH+6;}
      if(fb.improve){checkPage(20);const iLines=doc.splitTextToSize(fb.improve,contentW-16);const iH=iLines.length*5.5+14;doc.setFillColor(35,25,15);doc.roundedRect(margin,y,contentW,iH,3,3,'F');doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(245,158,11);doc.text('WHAT TO IMPROVE',margin+8,y+8);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(253,230,138);doc.text(iLines,margin+8,y+14);y+=iH+6;}
      if(fb.ideal){checkPage(20);const idLines=doc.splitTextToSize(fb.ideal,contentW-16);const idH=idLines.length*5.5+14;doc.setFillColor(15,23,42);doc.roundedRect(margin,y,contentW,idH,3,3,'F');doc.setFillColor(14,165,233);doc.roundedRect(margin,y,3,idH,1,1,'F');doc.setFont('helvetica','bold');doc.setFontSize(7.5);doc.setTextColor(14,165,233);doc.text('IDEAL ANSWER APPROACH',margin+8,y+8);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(186,230,253);doc.text(idLines,margin+8,y+14);y+=idH+6;}
    }
    doc.setFontSize(8); doc.setTextColor(71,85,105); doc.text(`Q${i+1} / ${questions.length}`,pageW-margin-16,pageH-10);
  });
  if(finalReport){
    doc.addPage(); doc.setFillColor(15,23,42); doc.rect(0,0,pageW,pageH,'F'); doc.setFillColor(139,92,246); doc.rect(0,0,pageW,2,'F');
    y=22; doc.setFont('helvetica','bold'); doc.setFontSize(20); doc.setTextColor(255,255,255); doc.text('Final Assessment',margin,y); y+=14;
    if(finalReport.strengths?.length){checkPage(15);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(16,185,129);doc.text('STRENGTHS',margin,y);y+=7;finalReport.strengths.forEach(s=>{checkPage(9);const ls=doc.splitTextToSize(`• ${s}`,contentW-6);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(167,243,208);doc.text(ls,margin+4,y);y+=ls.length*5.5+3;});y+=6;}
    if(finalReport.weaknesses?.length){checkPage(15);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(245,158,11);doc.text('AREAS TO IMPROVE',margin,y);y+=7;finalReport.weaknesses.forEach(w=>{checkPage(9);const lw=doc.splitTextToSize(`• ${w}`,contentW-6);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(253,230,138);doc.text(lw,margin+4,y);y+=lw.length*5.5+3;});y+=6;}
    if(finalReport.tips?.length){checkPage(15);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(167,139,250);doc.text('PRO TIPS',margin,y);y+=7;finalReport.tips.forEach(t=>{checkPage(9);const lt=doc.splitTextToSize(`• ${t}`,contentW-6);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(221,214,254);doc.text(lt,margin+4,y);y+=lt.length*5.5+3;});}
  }
  doc.save(`ResumeAI_MockInterview_${(setupData.role||'Report').replace(/\s+/g,'_')}.pdf`);
  toast.success('Report downloaded!');
};

// ── SIDEBAR NAV ITEM ──────────────────────────────────────────────────────
const SideNavItem = ({ icon: Icon, label, active, done, onClick }) => (
  <button
    onClick={onClick}
    className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-all text-left
      ${active
        ? 'bg-sky-500/15 text-sky-400 border border-sky-500/25'
        : done
          ? 'text-emerald-400 hover:bg-white/5'
          : 'text-slate-400 hover:bg-white/5 hover:text-slate-200'}`}
  >
    <span className={`flex-shrink-0 ${active ? 'text-sky-400' : done ? 'text-emerald-400' : 'text-slate-500'}`}>
      {done && !active ? <CheckCircle2 size={18} /> : <Icon size={18} />}
    </span>
    <span>{label}</span>
    {active && <ChevronRight size={14} className="ml-auto text-sky-400" />}
  </button>
);

// ── STAT CARD ─────────────────────────────────────────────────────────────
const StatCard = ({ icon: Icon, label, value, color = 'sky' }) => {
  const colors = {
    sky: 'text-sky-400 bg-sky-500/10',
    emerald: 'text-emerald-400 bg-emerald-500/10',
    yellow: 'text-yellow-400 bg-yellow-500/10',
    violet: 'text-violet-400 bg-violet-500/10',
  };
  return (
    <div className="bg-slate-900 border border-white/5 rounded-xl p-4 flex items-center gap-4">
      <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${colors[color]}`}>
        <Icon size={18} className={colors[color].split(' ')[0]} />
      </div>
      <div>
        <p className="text-xs text-slate-500">{label}</p>
        <p className="text-white font-semibold text-base">{value}</p>
      </div>
    </div>
  );
};

// ── MAIN COMPONENT ────────────────────────────────────────────────────────
export default function MockInterviewPage() {
  const [stage, setStage] = useState(STAGES.SETUP);
  const [setupTab, setSetupTab] = useState('form');
  const [form, setForm] = useState({ role: '', level: 'Junior', skills: '', company: '' });
  const [file, setFile] = useState(null);
  const [questions, setQuestions] = useState([]);
  const [currentQ, setCurrentQ] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [feedbacks, setFeedbacks] = useState([]);
  const [finalReport, setFinalReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [evalLoading, setEvalLoading] = useState(false);
  const [answerMode, setAnswerMode] = useState('voice');
  const [textAnswer, setTextAnswer] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [timeLeft, setTimeLeft] = useState(120);
  const [timerActive, setTimerActive] = useState(false);
  const [currentFeedback, setCurrentFeedback] = useState(null);

  const fileRef = useRef();
  const recognitionRef = useRef(null);
  const synthRef = useRef(window.speechSynthesis);
  const timerRef = useRef(null);
  const token = localStorage.getItem('token');

  useEffect(() => {
    if (timerActive && timeLeft > 0) {
      timerRef.current = setTimeout(() => setTimeLeft(t => t - 1), 1000);
    } else if (timeLeft === 0 && timerActive) {
      stopListening();
      toast('Time up! Submitting your answer.', { icon: '⏰' });
      handleSubmitAnswer();
    }
    return () => clearTimeout(timerRef.current);
  }, [timerActive, timeLeft]);

  useEffect(() => {
    if (stage === STAGES.INTERVIEWING && questions[currentQ]) {
      setTimeout(() => speakText(questions[currentQ].question), 600);
    }
  }, [stage, currentQ]);

  const speakText = (text) => {
    if (!synthRef.current) return;
    synthRef.current.cancel();
    const utt = new SpeechSynthesisUtterance(text);
    utt.lang = 'en-US'; utt.rate = 0.92; utt.pitch = 1;
    utt.onstart = () => setIsSpeaking(true);
    utt.onend = () => { setIsSpeaking(false); if (answerMode === 'voice') startListening(); };
    synthRef.current.speak(utt);
  };

  const startListening = () => {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) return toast.error('Speech recognition not supported. Use Chrome.');
    const rec = new SR();
    rec.lang = 'en-US'; rec.continuous = true; rec.interimResults = true;
    rec.onstart = () => { setIsListening(true); setTimerActive(true); setTimeLeft(120); };
    rec.onresult = (e) => {
      let final = '';
      for (let i = e.resultIndex; i < e.results.length; i++) {
        if (e.results[i].isFinal) final += e.results[i][0].transcript;
      }
      setTranscript(prev => prev + final);
    };
    rec.onerror = (e) => { if (e.error !== 'no-speech') toast.error('Mic error: ' + e.error); setIsListening(false); setTimerActive(false); };
    rec.onend = () => { setIsListening(false); setTimerActive(false); };
    recognitionRef.current = rec;
    rec.start();
  };

  const stopListening = () => { recognitionRef.current?.stop(); setIsListening(false); setTimerActive(false); };

  const generateQuestions = async () => {
    setLoading(true);
    try {
      let data;
      if (setupTab === 'form') {
        const res = await axios.post(`${API}/resume/mock-interview`, { ...form }, { headers: { Authorization: `Bearer ${token}` } });
        data = res.data;
      } else {
        if (!file) return toast.error('Upload a PDF first');
        const fd = new FormData(); fd.append('resume', file);
        const res = await axios.post(`${API}/resume/mock-interview-resume`, fd, { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'multipart/form-data' } });
        data = res.data;
      }
      setQuestions(data.questions || []);
      setAnswers(new Array(data.questions.length).fill(''));
      setFeedbacks(new Array(data.questions.length).fill(null));
      setStage(STAGES.READY);
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to generate questions');
    } finally { setLoading(false); }
  };

  const handleSubmitAnswer = async () => {
    const answer = answerMode === 'voice' ? transcript : textAnswer;
    if (!answer.trim()) return toast.error('Please give an answer first');
    stopListening(); synthRef.current?.cancel();
    const newAnswers = [...answers]; newAnswers[currentQ] = answer; setAnswers(newAnswers);
    setEvalLoading(true); setCurrentFeedback(null);
    try {
      const res = await axios.post(`${API}/resume/evaluate-answer`, {
        question: questions[currentQ].question, answer, role: form.role || 'General', level: form.level || 'Junior',
      }, { headers: { Authorization: `Bearer ${token}` } });
      const fb = res.data.feedback;
      const newFeedbacks = [...feedbacks]; newFeedbacks[currentQ] = fb;
      setFeedbacks(newFeedbacks); setCurrentFeedback(fb);
    } catch { toast.error('Evaluation failed'); }
    finally { setEvalLoading(false); }
  };

  const goNextQuestion = () => {
    setTranscript(''); setTextAnswer(''); setCurrentFeedback(null); synthRef.current?.cancel();
    if (currentQ + 1 >= questions.length) finishInterview();
    else setCurrentQ(q => q + 1);
  };

  const finishInterview = async () => {
    setStage(STAGES.FINISHED); setLoading(true);
    try {
      const res = await axios.post(`${API}/resume/final-report`, {
        questions: questions.map(q => q.question), answers, feedbacks, role: form.role || 'General', level: form.level || 'Junior',
      }, { headers: { Authorization: `Bearer ${token}` } });
      setFinalReport(res.data.report);
    } catch { toast.error('Could not generate final report'); }
    finally { setLoading(false); }
  };

  const resetAll = () => {
    synthRef.current?.cancel(); stopListening();
    setStage(STAGES.SETUP); setQuestions([]); setAnswers([]); setFeedbacks([]);
    setFinalReport(null); setCurrentQ(0); setTranscript(''); setTextAnswer('');
    setCurrentFeedback(null); setForm({ role: '', level: 'Junior', skills: '', company: '' }); setFile(null);
  };

  const avgScore = feedbacks.filter(Boolean).length
    ? Math.round(feedbacks.filter(Boolean).reduce((a, f) => a + (f?.score || 0), 0) / feedbacks.filter(Boolean).length) : 0;
  const fmt = (s) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;

  // ── SETUP STAGE ───────────────────────────────────────────────────────────
  if (stage === STAGES.SETUP) return (
    <div className="flex min-h-screen bg-slate-950">

      {/* LEFT SIDEBAR */}
      <aside className="w-64 flex-shrink-0 border-r border-white/5 p-5 flex flex-col gap-2">
        <div className="mb-4">
          <h2 className="text-white font-bold text-base">Mock Interview</h2>
          <p className="text-slate-500 text-xs mt-0.5">AI Interview Simulator</p>
        </div>

        <SideNavItem icon={Settings} label="Setup" active />
        <SideNavItem icon={BookOpen} label="Ready" />
        <SideNavItem icon={MessageSquare} label="Interview" />
        <SideNavItem icon={BarChart3} label="Report" />

        <div className="mt-auto pt-4 border-t border-white/5 space-y-3">
          <p className="text-xs text-slate-500 font-medium uppercase tracking-wider">Features</p>
          {[
            { icon: Mic, label: 'Voice Answers' },
            { icon: MessageSquare, label: 'Text Answers' },
            { icon: Zap, label: 'Instant Scoring' },
            { icon: FileText, label: 'PDF Report' },
          ].map(({ icon: Icon, label }) => (
            <div key={label} className="flex items-center gap-2 text-slate-400 text-xs">
              <Icon size={13} className="text-sky-500" />
              <span>{label}</span>
            </div>
          ))}
        </div>
      </aside>

      {/* MAIN CONTENT */}
      <main className="flex-1 overflow-y-auto">
        {/* Header bar */}
        <div className="flex items-center justify-between px-8 py-5 border-b border-white/5">
          <div>
            <h1 className="text-white font-bold text-xl">Interview Setup</h1>
            <p className="text-slate-400 text-sm mt-0.5">Configure your mock interview session</p>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-sky-500" />
            <span className="text-xs text-slate-400">Step 1 of 4</span>
          </div>
        </div>

        <div className="px-8 py-7">
          {/* Stats row */}
          <div className="grid grid-cols-4 gap-4 mb-8">
            <StatCard icon={Target} label="Mode" value="AI Powered" color="sky" />
            <StatCard icon={Clock} label="Per Question" value="2 Minutes" color="yellow" />
            <StatCard icon={Zap} label="Feedback" value="Instant" color="emerald" />
            <StatCard icon={FileText} label="Report" value="PDF Export" color="violet" />
          </div>

          {/* Tab switcher */}
          <div className="flex gap-1 mb-6 p-1 bg-slate-900 border border-white/5 rounded-xl w-fit">
            {[
              { key: 'form', icon: ClipboardList, label: 'Fill Form' },
              { key: 'resume', icon: Upload, label: 'Upload Resume' },
            ].map(({ key, icon: Icon, label }) => (
              <button key={key} onClick={() => setSetupTab(key)}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium transition-all ${
                  setupTab === key ? 'bg-sky-500 text-white shadow' : 'text-slate-400 hover:text-white'}`}>
                <Icon size={15} />
                {label}
              </button>
            ))}
          </div>

          {/* Form / Resume */}
          <div className="grid grid-cols-3 gap-6">
            <div className="col-span-2">
              {setupTab === 'form' ? (
                <div className="bg-slate-900 border border-white/5 rounded-2xl p-6">
                  <h3 className="text-white font-semibold mb-5 flex items-center gap-2">
                    <ClipboardList size={16} className="text-sky-400" /> Interview Details
                  </h3>
                  <div className="grid grid-cols-2 gap-4 mb-4">
                    <div>
                      <label className="block text-xs font-medium text-slate-400 mb-1.5">Target Role <span className="text-sky-400">*</span></label>
                      <input type="text" placeholder="e.g. Full Stack Developer" value={form.role}
                        onChange={e => setForm(p => ({ ...p, role: e.target.value }))}
                        className="w-full px-4 py-2.5 rounded-lg bg-slate-800 border border-white/10 text-white text-sm focus:outline-none focus:border-sky-500 placeholder:text-slate-600 transition" />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-400 mb-1.5">Experience Level</label>
                      <select value={form.level} onChange={e => setForm(p => ({ ...p, level: e.target.value }))}
                        className="w-full px-4 py-2.5 rounded-lg bg-slate-800 border border-white/10 text-white text-sm focus:outline-none focus:border-sky-500 transition">
                        {['Fresher', 'Junior', 'Mid-level', 'Senior'].map(o => <option key={o}>{o}</option>)}
                      </select>
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-400 mb-1.5">Your Skills <span className="text-sky-400">*</span></label>
                      <input type="text" placeholder="e.g. React, Node.js, MongoDB" value={form.skills}
                        onChange={e => setForm(p => ({ ...p, skills: e.target.value }))}
                        className="w-full px-4 py-2.5 rounded-lg bg-slate-800 border border-white/10 text-white text-sm focus:outline-none focus:border-sky-500 placeholder:text-slate-600 transition" />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-slate-400 mb-1.5">Target Company <span className="text-slate-600 font-normal">(optional)</span></label>
                      <input type="text" placeholder="e.g. Google, Infosys" value={form.company}
                        onChange={e => setForm(p => ({ ...p, company: e.target.value }))}
                        className="w-full px-4 py-2.5 rounded-lg bg-slate-800 border border-white/10 text-white text-sm focus:outline-none focus:border-sky-500 placeholder:text-slate-600 transition" />
                    </div>
                  </div>
                  <button onClick={generateQuestions} disabled={loading || !form.role || !form.skills}
                    className="w-full py-3 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white font-semibold text-sm hover:opacity-90 transition disabled:opacity-40 flex items-center justify-center gap-2">
                    {loading ? <><Loader2 size={16} className="animate-spin" /> Generating Questions...</> : <><Mic size={16} /> Start Mock Interview</>}
                  </button>
                </div>
              ) : (
                <div className="bg-slate-900 border border-white/5 rounded-2xl p-6">
                  <h3 className="text-white font-semibold mb-5 flex items-center gap-2">
                    <Upload size={16} className="text-sky-400" /> Upload Your Resume
                  </h3>
                  <div onClick={() => fileRef.current.click()}
                    className="border-2 border-dashed border-white/10 rounded-xl p-12 text-center cursor-pointer hover:border-sky-500/50 hover:bg-sky-500/5 transition mb-5">
                    <Upload size={32} className="mx-auto mb-3 text-slate-500" />
                    {file
                      ? <p className="text-sky-400 font-medium text-sm">{file.name}</p>
                      : <><p className="text-slate-300 text-sm font-medium">Click to upload resume PDF</p>
                          <p className="text-slate-500 text-xs mt-1">We'll generate questions based on your resume</p></>}
                    <input ref={fileRef} type="file" accept=".pdf" className="hidden" onChange={e => setFile(e.target.files[0])} />
                  </div>
                  <button onClick={generateQuestions} disabled={loading || !file}
                    className="w-full py-3 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white font-semibold text-sm hover:opacity-90 transition disabled:opacity-40 flex items-center justify-center gap-2">
                    {loading ? <><Loader2 size={16} className="animate-spin" /> Analyzing Resume...</> : <><Mic size={16} /> Start Mock Interview</>}
                  </button>
                </div>
              )}
            </div>

            {/* Right tip panel */}
            <div className="space-y-4">
              <div className="bg-slate-900 border border-white/5 rounded-2xl p-5">
                <p className="text-white font-semibold text-sm mb-4 flex items-center gap-2">
                  <Lightbulb size={15} className="text-yellow-400" /> How it works
                </p>
                <div className="space-y-3">
                  {[
                    { step: '01', text: 'Fill your details or upload resume' },
                    { step: '02', text: 'AI generates tailored questions' },
                    { step: '03', text: 'Answer by voice or text' },
                    { step: '04', text: 'Get instant scores & feedback' },
                    { step: '05', text: 'Download full PDF report' },
                  ].map(({ step, text }) => (
                    <div key={step} className="flex items-start gap-3">
                      <span className="text-xs font-bold text-sky-500 bg-sky-500/10 px-1.5 py-0.5 rounded flex-shrink-0 mt-0.5">{step}</span>
                      <p className="text-slate-400 text-xs leading-relaxed">{text}</p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-violet-500/10 border border-violet-500/20 rounded-2xl p-4">
                <p className="text-violet-300 font-semibold text-xs mb-2 flex items-center gap-1.5">
                  <Star size={13} /> Pro Tip
                </p>
                <p className="text-slate-400 text-xs leading-relaxed">Use Chrome for the best voice recognition experience. Ensure mic permissions are granted.</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );

  // ── READY STAGE ───────────────────────────────────────────────────────────
  if (stage === STAGES.READY) return (
    <div className="flex min-h-screen bg-slate-950">
      <aside className="w-64 flex-shrink-0 border-r border-white/5 p-5 flex flex-col gap-2">
        <div className="mb-4">
          <h2 className="text-white font-bold text-base">Mock Interview</h2>
          <p className="text-slate-500 text-xs mt-0.5">AI Interview Simulator</p>
        </div>
        <SideNavItem icon={Settings} label="Setup" done />
        <SideNavItem icon={BookOpen} label="Ready" active />
        <SideNavItem icon={MessageSquare} label="Interview" />
        <SideNavItem icon={BarChart3} label="Report" />
        <div className="mt-auto pt-4 border-t border-white/5">
          <div className="bg-slate-900 rounded-xl p-3 border border-white/5">
            <p className="text-xs text-slate-500 mb-1">Questions ready</p>
            <p className="text-white font-bold text-lg">{questions.length}</p>
          </div>
        </div>
      </aside>

      <main className="flex-1 overflow-y-auto">
        <div className="flex items-center justify-between px-8 py-5 border-b border-white/5">
          <div>
            <h1 className="text-white font-bold text-xl">Ready to Begin</h1>
            <p className="text-slate-400 text-sm mt-0.5">Choose your answer mode and start</p>
          </div>
          <span className="text-xs text-slate-400 flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-yellow-500" /> Step 2 of 4
          </span>
        </div>

        <div className="px-8 py-7 max-w-3xl">
          {/* Mode select */}
          <div className="grid grid-cols-2 gap-4 mb-7">
            {[
              { mode: 'voice', icon: Mic, title: 'Voice Mode', desc: 'Speak your answers aloud. Mic starts automatically after each question.' },
              { mode: 'text', icon: MessageSquare, title: 'Text Mode', desc: 'Type your answers. Great if you prefer keyboard or can\'t use mic.' },
            ].map(({ mode, icon: Icon, title, desc }) => (
              <button key={mode} onClick={() => setAnswerMode(mode)}
                className={`p-5 rounded-2xl border text-left transition-all ${answerMode === mode
                  ? 'bg-sky-500/10 border-sky-500/40 shadow-lg shadow-sky-500/10'
                  : 'bg-slate-900 border-white/5 hover:border-white/15'}`}>
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-3 ${answerMode === mode ? 'bg-sky-500/20' : 'bg-slate-800'}`}>
                  <Icon size={18} className={answerMode === mode ? 'text-sky-400' : 'text-slate-400'} />
                </div>
                <p className={`font-semibold text-sm mb-1 ${answerMode === mode ? 'text-sky-300' : 'text-white'}`}>{title}</p>
                <p className="text-xs text-slate-400 leading-relaxed">{desc}</p>
                {answerMode === mode && <div className="mt-3 flex items-center gap-1 text-xs text-sky-400 font-medium"><CheckCheck size={13} /> Selected</div>}
              </button>
            ))}
          </div>

          {/* Instructions */}
          <div className="bg-slate-900 border border-white/5 rounded-2xl p-5 mb-6">
            <p className="text-white font-semibold text-sm mb-4 flex items-center gap-2">
              <BookOpen size={15} className="text-sky-400" /> Instructions
            </p>
            <div className="grid grid-cols-2 gap-3">
              {[
                { icon: Volume2, text: 'AI reads each question aloud' },
                { icon: Clock, text: '2 minutes per question' },
                { icon: answerMode === 'voice' ? Mic : MessageSquare, text: answerMode === 'voice' ? 'Mic auto-starts after question' : 'Type your answer in the box' },
                { icon: Zap, text: 'Instant score & feedback after each answer' },
              ].map(({ icon: Icon, text }, i) => (
                <div key={i} className="flex items-start gap-2.5">
                  <div className="w-7 h-7 rounded-lg bg-sky-500/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                    <Icon size={13} className="text-sky-400" />
                  </div>
                  <p className="text-slate-300 text-sm">{text}</p>
                </div>
              ))}
            </div>
          </div>

          <button onClick={() => setStage(STAGES.INTERVIEWING)}
            className="w-full py-3.5 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white font-bold text-sm hover:opacity-90 transition flex items-center justify-center gap-2">
            <Play size={16} /> Begin Interview
          </button>
        </div>
      </main>
    </div>
  );

  // ── INTERVIEWING STAGE ────────────────────────────────────────────────────
  if (stage === STAGES.INTERVIEWING) {
    const q = questions[currentQ];
    const answered = !!currentFeedback;

    return (
      <div className="flex min-h-screen bg-slate-950">
        {/* Sidebar — question list */}
        <aside className="w-64 flex-shrink-0 border-r border-white/5 p-5 flex flex-col gap-2">
          <div className="mb-2">
            <h2 className="text-white font-bold text-base">Mock Interview</h2>
            <p className="text-slate-500 text-xs mt-0.5">{form.role || 'General'} · {form.level}</p>
          </div>

          <div className="space-y-1.5 flex-1 overflow-y-auto">
            {questions.map((_, i) => {
              const fb = feedbacks[i];
              const isCurrent = i === currentQ;
              const isDone = !!fb;
              return (
                <div key={i} className={`flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm transition-all
                  ${isCurrent ? 'bg-sky-500/15 border border-sky-500/25' : 'hover:bg-white/5'}`}>
                  <span className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold
                    ${isCurrent ? 'bg-sky-500 text-white' : isDone ? 'bg-emerald-500/20 text-emerald-400' : 'bg-slate-800 text-slate-500'}`}>
                    {isDone && !isCurrent ? <CheckCircle2 size={14} /> : i + 1}
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className={`text-xs truncate ${isCurrent ? 'text-sky-300 font-medium' : isDone ? 'text-slate-400' : 'text-slate-500'}`}>
                      Q{i + 1}: {q?.category || 'Question'}
                    </p>
                    {isDone && (
                      <p className={`text-xs font-bold ${scoreColor(fb.score)}`}>{fb.score}/100</p>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Timer in sidebar */}
          {timerActive && (
            <div className={`mt-auto p-3 rounded-xl border ${timeLeft < 30 ? 'bg-red-500/10 border-red-500/30' : 'bg-slate-900 border-white/5'}`}>
              <div className="flex items-center gap-2 mb-1">
                <Clock size={13} className={timeLeft < 30 ? 'text-red-400' : 'text-slate-400'} />
                <span className="text-xs text-slate-400">Time Left</span>
              </div>
              <p className={`font-mono font-bold text-xl ${timeLeft < 30 ? 'text-red-400' : 'text-white'}`}>{fmt(timeLeft)}</p>
            </div>
          )}
        </aside>

        <main className="flex-1 overflow-y-auto">
          {/* Top bar */}
          <div className="flex items-center justify-between px-8 py-4 border-b border-white/5">
            <div className="flex items-center gap-3">
              <span className="text-sm text-slate-400">Question {currentQ + 1} of {questions.length}</span>
              <div className="w-40 h-1.5 bg-slate-800 rounded-full overflow-hidden">
                <div className="h-1.5 bg-gradient-to-r from-sky-500 to-violet-600 rounded-full transition-all"
                  style={{ width: `${((currentQ) / questions.length) * 100}%` }} />
              </div>
            </div>
            <button onClick={() => setAnswerMode(m => m === 'voice' ? 'text' : 'voice')}
              className="flex items-center gap-2 text-xs text-slate-400 border border-white/10 px-3 py-1.5 rounded-lg hover:text-white hover:border-white/20 transition">
              {answerMode === 'voice' ? <><MessageSquare size={13} /> Switch to Text</> : <><Mic size={13} /> Switch to Voice</>}
            </button>
          </div>

          <div className="px-8 py-6 grid grid-cols-3 gap-6">
            {/* Question + answer (col 1-2) */}
            <div className="col-span-2 space-y-4">
              {/* Question card */}
              <div className="bg-slate-900 border border-white/5 rounded-2xl p-6">
                <div className="flex items-center gap-2 mb-3">
                  {q?.category && <span className="text-xs text-slate-500 bg-slate-800 px-2 py-1 rounded-full">{q.category}</span>}
                  {q?.difficulty && <span className="text-xs text-slate-500 bg-slate-800 px-2 py-1 rounded-full">{q.difficulty}</span>}
                </div>
                <p className="text-white font-medium text-base leading-relaxed">{q?.question}</p>
                {isSpeaking && (
                  <div className="flex items-center gap-2 mt-4 text-sky-400 text-xs">
                    <Volume2 size={14} className="animate-pulse" /> Reading question aloud...
                  </div>
                )}
                <button onClick={() => speakText(q?.question)}
                  className="mt-3 flex items-center gap-1.5 text-xs text-slate-500 hover:text-sky-400 transition">
                  <Volume2 size={13} /> Replay question
                </button>
              </div>

              {/* Answer area */}
              {!answered && (
                <div className="bg-slate-900 border border-white/5 rounded-2xl p-6">
                  <p className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
                    {answerMode === 'voice' ? <><Mic size={15} className="text-sky-400" /> Voice Answer</> : <><MessageSquare size={15} className="text-sky-400" /> Text Answer</>}
                  </p>

                  {answerMode === 'voice' ? (
                    <div>
                      <div className="flex flex-col items-center gap-4 mb-5">
                        <button onClick={isListening ? stopListening : startListening} disabled={isSpeaking}
                          className={`w-20 h-20 rounded-full flex items-center justify-center transition-all ${
                            isListening ? 'bg-red-500 shadow-xl shadow-red-500/30 animate-pulse' : 'bg-slate-800 hover:bg-sky-500/20 border-2 border-slate-600 hover:border-sky-500'
                          } disabled:opacity-30`}>
                          {isListening ? <Square size={24} className="text-white" /> : <Mic size={28} className="text-slate-300" />}
                        </button>
                        <p className="text-sm text-slate-400">
                          {isSpeaking ? 'Wait for question to finish...' : isListening ? 'Listening... Click to stop' : 'Click mic to start answering'}
                        </p>
                      </div>
                      {transcript && (
                        <div className="bg-slate-800 rounded-xl p-4 mb-4">
                          <p className="text-xs text-slate-500 mb-1.5">Your answer:</p>
                          <p className="text-sm text-slate-200 leading-relaxed">{transcript}</p>
                        </div>
                      )}
                      {transcript && (
                        <button onClick={handleSubmitAnswer} disabled={evalLoading}
                          className="w-full py-2.5 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white font-semibold text-sm hover:opacity-90 transition disabled:opacity-50 flex items-center justify-center gap-2">
                          {evalLoading ? <><Loader2 size={15} className="animate-spin" /> Evaluating...</> : <><CheckCheck size={15} /> Submit Answer</>}
                        </button>
                      )}
                    </div>
                  ) : (
                    <div>
                      <textarea value={textAnswer} onChange={e => setTextAnswer(e.target.value)}
                        placeholder="Type your answer here..." rows={5}
                        className="w-full px-4 py-3 rounded-xl bg-slate-800 border border-white/10 text-white text-sm focus:outline-none focus:border-sky-500 placeholder:text-slate-600 resize-none transition" />
                      <button onClick={handleSubmitAnswer} disabled={evalLoading || !textAnswer.trim()}
                        className="w-full mt-3 py-2.5 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white font-semibold text-sm hover:opacity-90 transition disabled:opacity-50 flex items-center justify-center gap-2">
                        {evalLoading ? <><Loader2 size={15} className="animate-spin" /> Evaluating...</> : <><CheckCheck size={15} /> Submit Answer</>}
                      </button>
                    </div>
                  )}
                </div>
              )}

              {/* Evaluating */}
              {evalLoading && (
                <div className="flex items-center justify-center gap-3 py-8 text-slate-400 text-sm bg-slate-900 border border-white/5 rounded-2xl">
                  <Loader2 size={18} className="text-sky-400 animate-spin" /> Evaluating your answer...
                </div>
              )}

              {/* Feedback */}
              {currentFeedback && !evalLoading && (
                <div className="space-y-3">
                  <div className={`flex items-center justify-between p-5 rounded-2xl border ${scoreBg(currentFeedback.score)}`}>
                    <div>
                      <p className="text-xs text-slate-500 mb-1">Your Score</p>
                      <p className={`text-4xl font-bold ${scoreColor(currentFeedback.score)}`}>
                        {currentFeedback.score}<span className="text-xl">/100</span>
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-slate-500 mb-1">Rating</p>
                      <p className={`font-semibold text-sm ${scoreColor(currentFeedback.score)}`}>
                        {currentFeedback.score >= 80 ? 'Excellent' : currentFeedback.score >= 60 ? 'Good' : 'Needs Work'}
                      </p>
                    </div>
                  </div>

                  {currentFeedback.good && (
                    <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-xl p-4">
                      <p className="text-xs text-emerald-400 font-semibold mb-1.5 flex items-center gap-1.5"><CheckCircle2 size={13} /> What you did well</p>
                      <p className="text-sm text-slate-300 leading-relaxed">{currentFeedback.good}</p>
                    </div>
                  )}
                  {currentFeedback.improve && (
                    <div className="bg-yellow-500/5 border border-yellow-500/20 rounded-xl p-4">
                      <p className="text-xs text-yellow-400 font-semibold mb-1.5 flex items-center gap-1.5"><AlertCircle size={13} /> What to improve</p>
                      <p className="text-sm text-slate-300 leading-relaxed">{currentFeedback.improve}</p>
                    </div>
                  )}
                  {currentFeedback.ideal && (
                    <div className="bg-sky-500/5 border border-sky-500/20 rounded-xl p-4">
                      <p className="text-xs text-sky-400 font-semibold mb-1.5 flex items-center gap-1.5"><Lightbulb size={13} /> Ideal answer approach</p>
                      <p className="text-sm text-slate-300 leading-relaxed">{currentFeedback.ideal}</p>
                    </div>
                  )}

                  <button onClick={goNextQuestion}
                    className="w-full py-3 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white font-bold text-sm hover:opacity-90 transition flex items-center justify-center gap-2">
                    {currentQ + 1 >= questions.length ? <><BarChart3 size={15} /> View Final Report</> : <>Next Question <ArrowRight size={15} /></>}
                  </button>
                </div>
              )}
            </div>

            {/* Right panel */}
            <div className="space-y-4">
              <div className="bg-slate-900 border border-white/5 rounded-2xl p-4">
                <p className="text-xs font-semibold text-slate-400 mb-3 flex items-center gap-1.5"><BarChart3 size={13} /> Progress</p>
                <div className="space-y-2">
                  <div className="flex justify-between text-xs text-slate-500">
                    <span>Completed</span><span>{feedbacks.filter(Boolean).length}/{questions.length}</span>
                  </div>
                  <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-2 bg-gradient-to-r from-sky-500 to-violet-600 rounded-full transition-all"
                      style={{ width: `${(feedbacks.filter(Boolean).length / questions.length) * 100}%` }} />
                  </div>
                </div>
                {feedbacks.filter(Boolean).length > 0 && (
                  <div className="mt-3 pt-3 border-t border-white/5">
                    <p className="text-xs text-slate-500 mb-1">Avg Score So Far</p>
                    <p className={`text-xl font-bold ${scoreColor(avgScore)}`}>{avgScore}<span className="text-sm">/100</span></p>
                  </div>
                )}
              </div>

              <div className="bg-slate-900 border border-white/5 rounded-2xl p-4">
                <p className="text-xs font-semibold text-slate-400 mb-3">Score Breakdown</p>
                <div className="space-y-2">
                  {questions.map((_, i) => {
                    const fb = feedbacks[i];
                    return (
                      <div key={i} className="flex items-center gap-2">
                        <span className="text-xs text-slate-500 w-5">Q{i+1}</span>
                        <div className="flex-1 h-1.5 bg-slate-800 rounded-full overflow-hidden">
                          {fb && <div className={`h-1.5 rounded-full ${scoreBar(fb.score)}`} style={{ width: `${fb.score}%` }} />}
                        </div>
                        <span className={`text-xs font-bold w-8 text-right ${fb ? scoreColor(fb.score) : 'text-slate-700'}`}>
                          {fb ? `${fb.score}` : '—'}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    );
  }

  // ── FINISHED STAGE ────────────────────────────────────────────────────────
  if (stage === STAGES.FINISHED) return (
    <div className="flex min-h-screen bg-slate-950">
      <aside className="w-64 flex-shrink-0 border-r border-white/5 p-5 flex flex-col gap-2">
        <div className="mb-4">
          <h2 className="text-white font-bold text-base">Mock Interview</h2>
          <p className="text-slate-500 text-xs mt-0.5">{form.role || 'General'} · {form.level}</p>
        </div>
        <SideNavItem icon={Settings} label="Setup" done />
        <SideNavItem icon={BookOpen} label="Ready" done />
        <SideNavItem icon={MessageSquare} label="Interview" done />
        <SideNavItem icon={BarChart3} label="Report" active />

        <div className="mt-auto pt-4 border-t border-white/5 space-y-2">
          <button onClick={resetAll}
            className="w-full flex items-center gap-2 px-4 py-2.5 rounded-xl border border-white/10 text-slate-300 text-sm font-medium hover:bg-white/5 transition">
            <RotateCcw size={14} /> New Interview
          </button>
          {finalReport && (
            <button onClick={() => downloadReportPDF(questions, answers, feedbacks, finalReport, form)}
              className="w-full flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-sky-500 to-violet-600 text-white text-sm font-semibold hover:opacity-90 transition">
              <Download size={14} /> Download PDF
            </button>
          )}
        </div>
      </aside>

      <main className="flex-1 overflow-y-auto">
        <div className="flex items-center justify-between px-8 py-5 border-b border-white/5">
          <div>
            <h1 className="text-white font-bold text-xl flex items-center gap-2">
              <Trophy size={20} className="text-yellow-400" /> Interview Complete
            </h1>
            <p className="text-slate-400 text-sm mt-0.5">Here's your full performance report</p>
          </div>
        </div>

        <div className="px-8 py-6">
          {/* Top stats */}
          <div className="grid grid-cols-4 gap-4 mb-6">
            <div className={`col-span-1 p-5 rounded-2xl border ${scoreBg(avgScore)} flex flex-col items-center justify-center text-center`}>
              <p className="text-xs text-slate-500 mb-1">Overall Score</p>
              <p className={`text-4xl font-bold ${scoreColor(avgScore)}`}>{avgScore}<span className="text-xl">/100</span></p>
              <p className={`text-xs mt-1 ${scoreColor(avgScore)}`}>
                {avgScore >= 80 ? 'Excellent!' : avgScore >= 60 ? 'Good Effort' : 'Keep Practicing'}
              </p>
            </div>
            <StatCard icon={ClipboardList} label="Total Questions" value={questions.length} color="sky" />
            <StatCard icon={CheckCheck} label="Answered" value={answers.filter(Boolean).length} color="emerald" />
            <StatCard icon={TrendingUp} label="Avg Score" value={`${avgScore}%`} color={avgScore >= 80 ? 'emerald' : avgScore >= 60 ? 'yellow' : 'sky'} />
          </div>

          <div className="grid grid-cols-3 gap-6">
            {/* Score breakdown + final report */}
            <div className="col-span-2 space-y-5">
              {/* Score bars */}
              <div className="bg-slate-900 border border-white/5 rounded-2xl p-5">
                <p className="text-white font-semibold text-sm mb-4 flex items-center gap-2">
                  <BarChart3 size={15} className="text-sky-400" /> Score Breakdown
                </p>
                <div className="space-y-3">
                  {questions.map((q, i) => {
                    const fb = feedbacks[i];
                    return (
                      <div key={i} className="flex items-center gap-3">
                        <span className="text-xs text-slate-500 w-6">Q{i+1}</span>
                        <div className="flex-1 h-2 bg-slate-800 rounded-full overflow-hidden">
                          <div className={`h-2 rounded-full transition-all ${scoreBar(fb?.score || 0)}`} style={{ width: `${fb?.score || 0}%` }} />
                        </div>
                        <span className={`text-xs font-bold w-12 text-right ${scoreColor(fb?.score || 0)}`}>{fb?.score || 0}%</span>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Final report */}
              {loading && (
                <div className="flex items-center justify-center gap-3 py-10 text-slate-400 text-sm bg-slate-900 border border-white/5 rounded-2xl">
                  <Loader2 size={18} className="text-sky-400 animate-spin" /> Generating final report...
                </div>
              )}

              {finalReport && !loading && (
                <div className="space-y-4">
                  {finalReport.summary && (
                    <div className="bg-slate-900 border border-white/5 rounded-2xl p-5">
                      <p className="text-white font-semibold text-sm mb-2 flex items-center gap-2">
                        <FileText size={15} className="text-sky-400" /> Overall Summary
                      </p>
                      <p className="text-sm text-slate-300 leading-relaxed">{finalReport.summary}</p>
                    </div>
                  )}
                  {finalReport.strengths?.length > 0 && (
                    <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-2xl p-5">
                      <p className="text-emerald-400 font-semibold text-sm mb-3 flex items-center gap-2"><CheckCircle2 size={15} /> Your Strengths</p>
                      {finalReport.strengths.map((s, i) => <p key={i} className="text-sm text-slate-300 mb-1.5">• {s}</p>)}
                    </div>
                  )}
                  {finalReport.weaknesses?.length > 0 && (
                    <div className="bg-yellow-500/5 border border-yellow-500/20 rounded-2xl p-5">
                      <p className="text-yellow-400 font-semibold text-sm mb-3 flex items-center gap-2"><AlertCircle size={15} /> Areas to Improve</p>
                      {finalReport.weaknesses.map((w, i) => <p key={i} className="text-sm text-slate-300 mb-1.5">• {w}</p>)}
                    </div>
                  )}
                  {finalReport.tips?.length > 0 && (
                    <div className="bg-violet-500/5 border border-violet-500/20 rounded-2xl p-5">
                      <p className="text-violet-400 font-semibold text-sm mb-3 flex items-center gap-2"><Lightbulb size={15} /> Pro Tips</p>
                      {finalReport.tips.map((t, i) => <p key={i} className="text-sm text-slate-300 mb-1.5">• {t}</p>)}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Right — per-Q mini cards */}
            <div className="space-y-3">
              <p className="text-white font-semibold text-sm flex items-center gap-2">
                <ClipboardList size={15} className="text-sky-400" /> Per Question
              </p>
              {questions.map((q, i) => {
                const fb = feedbacks[i];
                return (
                  <div key={i} className={`p-3 rounded-xl border ${fb ? scoreBg(fb.score) : 'bg-slate-900 border-white/5'}`}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-xs text-slate-400">Q{i+1}</span>
                      {fb ? <span className={`text-xs font-bold ${scoreColor(fb.score)}`}>{fb.score}/100</span>
                           : <span className="text-xs text-slate-600">—</span>}
                    </div>
                    <p className="text-xs text-slate-400 truncate">{q.question?.slice(0, 60)}…</p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}